### PR TITLE
Update links in meta.yaml

### PR DESCRIPTION
**Pull request by thelfer**

### CODE REVIEW

**Comment by Krande** [comment]
@conda-forge-admin, please rerender

**Comment by Krande** [comment]
@thelfer i think this looks good. Did you want to produce a new batch of packages with the updated metadata or is it enough that the feedstock and anaconda info pages are updated?

If updating the pages is all you need I can merge this. If you want to build a new batch of packages, you will need to bump the build number from 0 to 1 in the meta.yaml

**Comment by thelfer** [comment]
@Krande It is ok for me.
Many thanks for maintaining the `mfront` package !
I had a look at it just because I ported `TFEL` to `pybind11`, which will probably have an impact on the `conda` package for the next release (end of 2025).
Also, I need to check, but the package for not properly working on `windows`. If I remember things correctly, it is because the `TFELHOME` environment variable is not set and a strange error when using `ninja` within `Powershell`. I need to investigate that.
Best,
Thomas

**Comment by Krande** [comment]
No problem :) Thank you for sharing mfront and mgis with the rest of us!

Okay, then I'll merge this as is. 

If you find any issues related to the conda package of mfront on windows (or any platform really), feel free to make a new issue in this feedstock (or just tag me in any relevant issues in the mfront or mgis main repos). Then I can help debug it. 

We can also add more tests to the conda build scripts ensure that we catch more issue

Best Regards
Kristoffer

**Comment by Krande** [comment]
BTW. If you are moving towards a new python binding wrapper library. Have you considered nanobind? 

https://nanobind.readthedocs.io/en/latest/why.html

**Comment by thelfer** [comment]
@Krane, I did use `nanobind` in another context. I think that it's a great tool.

The main advantage of `pybind11` is that it allows to embed the interpreter in `C++` allowing a bidirectional exchange.
This is not mandatory of `TFEL` and `MGIS` but for some of our internal projects written in `C++` with `python` plugins.

In the end, I choose `pybind11` because it's a common solution for all my needs, but if I ever need to switch to `nanobind` for any reason, I know that the transition is straightforward.

**Pull request merged**
