### PR TITLE
Add fortran support for windows

### PR DESCRIPTION
**Pull request by Krande**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Krande** [comment]
@conda-forge-admin, please rerender

**Comment by Krande** [comment]
Oh, it wasn't quite ready yet I think :)  I forgot to set this as a draft

(don't think it's a problem though)

But we should add the linux builds back if there's another auto update PR

**Comment by Krande** [comment]
I didn't expect it to work almost on my first attempt at compiling with flang!

**Comment by ldallolio** [comment]
I was wondering... :-D but it passed the tests so... why not ? ;-)

Il giorno ven 12 apr 2024 alle ore 14:32 Kristoffer Andersen <
***@***.***> ha scritto:

**Comment by Krande** [comment]
> I was wondering... :-D but it passed the tests so... why not ? ;-) 

Yeah, I agree :) Then I move on to add fortran to mgis :)

**Pull request merged**
